[package]
name = "private_voting"
type = "contract"
authors = ["Ankit Agrawal"]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.67.1", directory="noir-projects/aztec-nr/aztec" }